### ISSUE TITLE
"Unknown string format" when trying the example

### ISSUE THREAD

**Issue by soerface** [flipdot/ascii-flyers#1]
I tried the example from the README

```
./ascii-flyer.py --title "Brennende Computer" \                             1 ↵ 
                 --description "Daten fangen Feuer? Löschen Sie sie sofort\!" \
                 --datetime "$(date --date='next tuesday 19:23')" \
                 --type "Predigt"\
                 --preview
```

I get this:

```
Traceback (most recent call last):
  File "./ascii-flyer.py", line 211, in <module>
    make_pdf_file(PDF_PATH, args)
  File "./ascii-flyer.py", line 184, in make_pdf_file
    draw_text_front(x * box_width + BORDER_H, y * box_height + BORDER_V, c, args, color_fg)
  File "./ascii-flyer.py", line 112, in draw_text_front
    for i, line in enumerate(get_text_invitation_front(args.event_title, args.event_datetime, args.event_type).split('\n')[::-1]):
  File "./ascii-flyer.py", line 92, in get_text_invitation_front
    event_datetime_reparsed = datetime.datetime.strftime(parse(event_datetime), DATE_FORMAT)
  File "/usr/lib/python3/dist-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python3/dist-packages/dateutil/parser/_parser.py", line 648, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: ('Unknown string format:', 'Di 28. Jan 19:23:00 CET 2020'
```

**Comment by flxai** [comment]
This most likely is a but having to do with localization. Does it work when you start it while setting `LC_TIME` temporarily?

```bash
LC_TIME="en_US.UTF-8" ./ascii-flyer.py [...]
```

*`[...]` marks the other parameters.*

What is the output of `locale` on your machine?

**Comment by soerface** [comment]
**--iso=m**

```
date --date='next tuesday 19:23' --iso=m
```

https://forum.flipdot.org/t/flyer-generator-doesnt-work-on-my-machine/3859/2

https://github.com/flipdot/ascii-flyers/commit/d7c5444d9a7fec3bc23071b9aba4c032ad455d8d
